"""empty message

Revision ID: 1d239589c41f
Revises: None
Create Date: 2015-01-04 18:52:39.690665

"""

# revision identifiers, used by Alembic.
revision = '1d239589c41f'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
